spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_crn
    username: root
    password: 19982001

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 10MB